# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f5cc9620240f6753177b39615dbcb3902374accca91a50df2c013f9bd8acbe01d4f5609b06bd6720de24270f665a9555ade1a78e674e16193c0c644a8ff681

test:
  secret_key_base: 86a63bc93639e7d2dcdc33321bd8ab21dcc99c8beec03510e26557115cbfe391f7d08b00887db8bae2f68169aaadc4a2349cff0466d4c7b20efc95e64cac0f87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
